import { defineField, defineType } from "sanity";

/**
 * The /contact page — hero copy, business hours table, service-areas list,
 * emergency-contact section. Mailing address + email + phone live on
 * siteSettings (already wired); this singleton owns the rest of the page.
 */
export default defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "document",
  description:
    "All editable copy on /contact: hero, business hours table, service-areas list, emergency-contact section. Mailing address + email + phone come from Site Settings.",
  groups: [
    { name: "english", title: "English", default: true },
    { name: "russian", title: "Русский (Russian)" },
    { name: "details", title: "Hours & Service Areas" },
    { name: "hero", title: "Hero Buttons" },
    { name: "form", title: "Form Section" },
    { name: "info", title: "Info Card Labels" },
    { name: "faqs", title: "FAQs" },
    { name: "bottomCta", title: "Bottom CTA" },
  ],
  fields: [
    defineField({
      name: "heroHeading",
      title: "Hero Heading (English)",
      type: "string",
      group: "english",
      initialValue: "Get in Touch",
    }),
    defineField({
      name: "heroHeadingRu",
      title: "Hero Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Свяжитесь с нами",
    }),
    defineField({
      name: "heroSubheading",
      title: "Hero Subheading (English)",
      type: "text",
      rows: 3,
      group: "english",
    }),
    defineField({
      name: "heroSubheadingRu",
      title: "Hero Subheading (Русский)",
      type: "text",
      rows: 3,
      group: "russian",
    }),
    defineField({
      name: "businessHoursHeading",
      title: "Business Hours Heading (English)",
      type: "string",
      group: "english",
      initialValue: "Business Hours",
    }),
    defineField({
      name: "businessHoursHeadingRu",
      title: "Business Hours Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Часы работы",
    }),
    defineField({
      name: "businessHours",
      title: "Business Hours",
      type: "array",
      group: "details",
      of: [
        {
          type: "object",
          name: "hoursRow",
          fields: [
            { name: "label", type: "string", title: "Day(s) Label (English)" },
            { name: "labelRu", type: "string", title: "Day(s) Label (Русский)" },
            { name: "hours", type: "string", title: "Hours (English)" },
            { name: "hoursRu", type: "string", title: "Hours (Русский)" },
          ],
          preview: {
            select: { title: "label", subtitle: "hours" },
          },
        },
      ],
      description: "Each row = one day or day range. e.g. label='Monday - Friday' hours='9:00 AM - 6:00 PM EST'.",
    }),
    defineField({
      name: "serviceAreasHeading",
      title: "Service Areas Heading (English)",
      type: "string",
      group: "english",
      initialValue: "Service Areas",
    }),
    defineField({
      name: "serviceAreasHeadingRu",
      title: "Service Areas Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Регионы обслуживания",
    }),
    defineField({
      name: "serviceAreas",
      title: "Service Areas",
      type: "array",
      group: "details",
      of: [
        {
          type: "object",
          name: "serviceArea",
          fields: [
            { name: "label", type: "string", title: "Description (English)" },
            { name: "labelRu", type: "string", title: "Description (Русский)" },
          ],
          preview: { select: { title: "label" } },
        },
      ],
    }),
    defineField({
      name: "emergencyHeading",
      title: "Emergency Contact Heading (English)",
      type: "string",
      group: "english",
      initialValue: "Emergency Contact",
    }),
    defineField({
      name: "emergencyHeadingRu",
      title: "Emergency Contact Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Экстренная связь",
    }),
    defineField({
      name: "emergencyBody",
      title: "Emergency Contact Body (English)",
      type: "text",
      group: "english",
      rows: 3,
      description:
        "Body text that appears in the emergency contact callout. The phone number itself is rendered separately (from Site Settings).",
    }),
    defineField({
      name: "emergencyBodyRu",
      title: "Emergency Contact Body (Русский)",
      type: "text",
      group: "russian",
      rows: 3,
    }),
    defineField({
      name: "addressLabel",
      title: "Address Label (English)",
      type: "string",
      group: "english",
      description: "Small subtitle under the mailing address (e.g. 'Headquarters & Operations Center').",
      initialValue: "Headquarters & Operations Center",
    }),
    defineField({
      name: "addressLabelRu",
      title: "Address Label (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Штаб-квартира и операционный центр",
    }),
    defineField({
      name: "primaryEmailDescription",
      title: "Primary Email Subtitle (English)",
      type: "string",
      group: "english",
      initialValue: "Primary contact for inquiries",
    }),
    defineField({
      name: "primaryEmailDescriptionRu",
      title: "Primary Email Subtitle (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Основной контакт для вопросов",
    }),
    defineField({
      name: "primaryPhoneDescription",
      title: "Primary Phone Subtitle (English)",
      type: "string",
      group: "english",
      initialValue: "Text & Call Available Monday - Friday",
    }),
    defineField({
      name: "primaryPhoneDescriptionRu",
      title: "Primary Phone Subtitle (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Звонки и сообщения: понедельник — пятница",
    }),

    // ── Hero CTA buttons ─────────────────────────────────────────────────────
    defineField({
      name: "heroPrimaryCtaLabel",
      title: "Hero Primary Button (English)",
      type: "string",
      group: "hero",
      initialValue: "Send a Message",
      description: "Scrolls to the contact form on the same page.",
    }),
    defineField({
      name: "heroPrimaryCtaLabelRu",
      title: "Hero Primary Button (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Написать нам",
    }),
    defineField({
      name: "heroSecondaryCtaLabel",
      title: "Hero Secondary Button — English Mode",
      type: "string",
      group: "hero",
      description:
        "Shown to non-Central-Asia visitors next to the primary button. Defaults to the phone number from Site Settings if blank.",
    }),
    defineField({
      name: "heroWhatsappCtaLabel",
      title: "Hero WhatsApp Button — Central Asia Mode",
      type: "string",
      group: "hero",
      initialValue: "WhatsApp",
      description:
        "Shown to Central-Asia visitors instead of the phone-call CTA.",
    }),
    defineField({
      name: "heroWhatsappCtaLabelRu",
      title: "Hero WhatsApp Button (Русский)",
      type: "string",
      group: "russian",
      initialValue: "WhatsApp",
    }),
    defineField({
      name: "whatsappUrl",
      title: "WhatsApp URL",
      type: "url",
      group: "hero",
      initialValue: "https://wa.me/13865171527",
      validation: (R) =>
        R.uri({ scheme: ["http", "https"], allowRelative: false }),
      description: "Used by both the hero WhatsApp button and the info card.",
    }),

    // ── Form section ─────────────────────────────────────────────────────────
    defineField({
      name: "formHeading",
      title: "Form Section Heading (English)",
      type: "string",
      group: "form",
      initialValue: "Send Us a Message",
    }),
    defineField({
      name: "formHeadingRu",
      title: "Form Section Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Напишите нам",
    }),
    defineField({
      name: "formSubheading",
      title: "Form Section Subheading (English)",
      type: "string",
      group: "form",
      initialValue: "We typically respond within 24-48 hours.",
    }),
    defineField({
      name: "formSubheadingRu",
      title: "Form Section Subheading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Как правило, мы отвечаем в течение 24–48 часов.",
    }),

    // ── Right-column Contact Info card labels ────────────────────────────────
    defineField({
      name: "infoHeading",
      title: "Info Card Heading (English)",
      type: "string",
      group: "info",
      initialValue: "Contact Information",
    }),
    defineField({
      name: "infoHeadingRu",
      title: "Info Card Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Контактная информация",
    }),
    defineField({
      name: "emailLabel",
      title: "Email Label (English)",
      type: "string",
      group: "info",
      initialValue: "Email",
    }),
    defineField({
      name: "emailLabelRu",
      title: "Email Label (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Электронная почта",
    }),
    defineField({
      name: "phoneLabel",
      title: "Phone Label (English)",
      type: "string",
      group: "info",
      initialValue: "Phone",
    }),
    defineField({
      name: "phoneLabelRu",
      title: "Phone Label (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Телефон",
    }),
    defineField({
      name: "phoneCallNote",
      title: "Phone Note (English)",
      type: "string",
      group: "info",
      initialValue: "Call or text, Monday - Friday",
    }),
    defineField({
      name: "phoneCallNoteRu",
      title: "Phone Note (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Звонки и SMS, понедельник – пятница",
    }),
    defineField({
      name: "whatsappBlockNote",
      title: "WhatsApp Note (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Напишите нам в WhatsApp",
      description:
        "Subtitle under the WhatsApp row in the info card. Only shown in Central Asia.",
    }),
    defineField({
      name: "addressBlockLabel",
      title: "Address Block Label (English)",
      type: "string",
      group: "info",
      initialValue: "Address",
    }),
    defineField({
      name: "addressBlockLabelRu",
      title: "Address Block Label (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Адрес",
    }),
    defineField({
      name: "hoursBlockLabel",
      title: "Hours Block Label (English)",
      type: "string",
      group: "info",
      initialValue: "Hours",
    }),
    defineField({
      name: "hoursBlockLabelRu",
      title: "Hours Block Label (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Часы работы",
    }),
    defineField({
      name: "serviceAreasBlockLabel",
      title: "Service Areas Block Label (English)",
      type: "string",
      group: "info",
      initialValue: "Service Areas",
    }),
    defineField({
      name: "serviceAreasBlockLabelRu",
      title: "Service Areas Block Label (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Регионы присутствия",
    }),
    defineField({
      name: "serviceAreasBlockShort",
      title: "Service Areas Short (English)",
      type: "string",
      group: "info",
      initialValue: "Kazakhstan, Kyrgyzstan, Uzbekistan",
      description:
        "Short one-line version shown in the info card. The full bulleted list above ('serviceAreas') is shown in the deeper ContactInfo component.",
    }),
    defineField({
      name: "serviceAreasBlockShortRu",
      title: "Service Areas Short (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Казахстан, Кыргызстан, Узбекистан",
    }),
    defineField({
      name: "serviceAreasBlockNote",
      title: "Service Areas Note (English)",
      type: "string",
      group: "info",
      initialValue: "Remote consultations worldwide",
    }),
    defineField({
      name: "serviceAreasBlockNoteRu",
      title: "Service Areas Note (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Удалённые консультации по всему миру",
    }),

    // ── FAQs ────────────────────────────────────────────────────────────────
    defineField({
      name: "faqsHeading",
      title: "FAQ Heading (English)",
      type: "string",
      group: "faqs",
      initialValue: "Common Questions",
    }),
    defineField({
      name: "faqsHeadingRu",
      title: "FAQ Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Частые вопросы",
    }),
    defineField({
      name: "faqs",
      title: "FAQ Items",
      type: "array",
      group: "faqs",
      of: [
        {
          type: "object",
          name: "contactFaq",
          fields: [
            { name: "question", type: "string", title: "Question (English)" },
            { name: "questionRu", type: "string", title: "Question (Русский)" },
            { name: "answer", type: "text", rows: 4, title: "Answer (English)" },
            { name: "answerRu", type: "text", rows: 4, title: "Answer (Русский)" },
          ],
          preview: { select: { title: "question" } },
        },
      ],
      description:
        "Frequently asked questions shown in the accordion below the contact form.",
    }),

    // ── Bottom CTA banner ───────────────────────────────────────────────────
    defineField({
      name: "bottomCtaHeading",
      title: "Bottom CTA Heading (English)",
      type: "string",
      group: "bottomCta",
      initialValue: "Ready to Make an Impact?",
    }),
    defineField({
      name: "bottomCtaHeadingRu",
      title: "Bottom CTA Heading (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Готовы изменить жизни?",
    }),
    defineField({
      name: "bottomCtaSubheading",
      title: "Bottom CTA Subheading (English)",
      type: "text",
      group: "bottomCta",
      rows: 3,
      initialValue:
        "Learn about our programs, become a volunteer mentor, or support entrepreneurs building businesses in Central Asia.",
    }),
    defineField({
      name: "bottomCtaSubheadingRu",
      title: "Bottom CTA Subheading (Русский)",
      type: "text",
      group: "russian",
      rows: 3,
      initialValue:
        "Узнайте о наших программах, станьте волонтёром-наставником или поддержите предпринимателей, строящих бизнес в Центральной Азии.",
    }),
    defineField({
      name: "bottomCtaPrimaryLabel",
      title: "Bottom CTA Primary Button (English)",
      type: "string",
      group: "bottomCta",
      initialValue: "Get Involved",
    }),
    defineField({
      name: "bottomCtaPrimaryLabelRu",
      title: "Bottom CTA Primary Button (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Принять участие",
    }),
    defineField({
      name: "bottomCtaPrimaryUrl",
      title: "Bottom CTA Primary URL",
      type: "string",
      group: "bottomCta",
      initialValue: "/get-involved",
    }),
    defineField({
      name: "bottomCtaSecondaryLabel",
      title: "Bottom CTA Secondary Button (English)",
      type: "string",
      group: "bottomCta",
      initialValue: "Explore Our Programs",
    }),
    defineField({
      name: "bottomCtaSecondaryLabelRu",
      title: "Bottom CTA Secondary Button (Русский)",
      type: "string",
      group: "russian",
      initialValue: "Наши программы",
    }),
    defineField({
      name: "bottomCtaSecondaryUrl",
      title: "Bottom CTA Secondary URL",
      type: "string",
      group: "bottomCta",
      initialValue: "/programs-and-impact",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Contact Page" }),
  },
});
