import { defineField, defineType } from "sanity";

export default defineType({
  name: "successStory",
  title: "Success Story",
  type: "document",
  description:
    "Real stories from program participants. Add new stories as participants complete programs; mark old ones inactive instead of deleting.",
  groups: [
    { name: "english", title: "English", default: true },
    { name: "russian", title: "Русский (Russian)" },
    { name: "media", title: "Photo & Hero" },
    { name: "details", title: "Details" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Story Title (English)",
      type: "string",
      group: "english",
      description:
        "Full headline shown on the listing card and detail page (e.g. 'From Seamstress to Fashion Entrepreneur').",
      validation: (R) => R.required().max(180),
    }),
    defineField({
      name: "titleRu",
      title: "Story Title (Русский)",
      type: "string",
      group: "russian",
    }),
    defineField({
      name: "name",
      title: "Participant Name",
      type: "string",
      group: "details",
      validation: (R) => R.required(),
    }),
    defineField({
      name: "nameRu",
      title: "Participant Name (Русский)",
      type: "string",
      group: "russian",
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      group: "details",
      options: { source: "title", maxLength: 96 },
    }),
    defineField({
      name: "business",
      title: "Business Name",
      type: "string",
      group: "details",
      description: "e.g. 'Thread & Thistle Apparel'.",
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      group: "details",
      description: "City, Country (e.g. 'Almaty, Kazakhstan').",
    }),
    defineField({
      name: "locationRu",
      title: "Location (Русский)",
      type: "string",
      group: "russian",
    }),
    defineField({
      name: "excerpt",
      title: "Excerpt (English)",
      type: "text",
      group: "english",
      rows: 3,
      description:
        "Short summary shown on the success-stories listing (1-3 sentences).",
      validation: (R) => R.max(400),
    }),
    defineField({
      name: "excerptRu",
      title: "Excerpt (Русский)",
      type: "text",
      group: "russian",
      rows: 3,
    }),
    defineField({
      name: "impact",
      title: "Impact Bullets (English)",
      type: "array",
      of: [{ type: "string" }],
      group: "english",
      description:
        "Short, punchy outcomes. The first one is shown on the listing card.",
    }),
    defineField({
      name: "impactRu",
      title: "Impact Bullets (Русский)",
      type: "array",
      of: [{ type: "string" }],
      group: "russian",
    }),
    defineField({
      name: "program",
      title: "Program",
      type: "reference",
      to: [{ type: "programPage" }],
      group: "details",
      description: "Which BBB program did they go through?",
    }),
    defineField({
      name: "heroImageUrl",
      title: "Hero Image URL",
      type: "string",
      group: "media",
      description:
        "Direct URL (Unsplash, etc.). For uploaded images use the 'Photo' field below.",
    }),
    defineField({
      name: "photo",
      title: "Photo (Sanity-uploaded)",
      type: "image",
      group: "media",
      options: { hotspot: true },
      fields: [{ name: "alt", type: "string", title: "Alt text" }],
      description:
        "Optional uploaded image. If set, takes priority over Hero Image URL.",
    }),
    defineField({
      name: "story",
      title: "Long-form Story (English)",
      type: "blockContent",
      group: "english",
      description: "Full narrative — used on the detail page.",
    }),
    defineField({
      name: "storyRu",
      title: "Long-form Story (Русский)",
      type: "blockContent",
      group: "russian",
    }),
    defineField({
      name: "metrics",
      title: "Metric Cards",
      type: "array",
      group: "details",
      of: [
        {
          type: "object",
          name: "metric",
          fields: [
            { name: "label", type: "string", title: "Label (English)" },
            { name: "labelRu", type: "string", title: "Label (Русский)" },
            { name: "value", type: "string", title: "Value (e.g. '3x Revenue')" },
            { name: "description", type: "string", title: "Description (English)" },
            { name: "descriptionRu", type: "string", title: "Description (Русский)" },
          ],
          preview: { select: { title: "value", subtitle: "label" } },
        },
      ],
      description: "Stat-card style metrics shown on the detail page (revenue growth, customers, etc.).",
    }),
    defineField({
      name: "timeline",
      title: "Timeline Phases",
      type: "array",
      group: "details",
      of: [
        {
          type: "object",
          name: "timelinePhase",
          fields: [
            { name: "phase", type: "string", title: "Phase Name (English)" },
            { name: "phaseRu", type: "string", title: "Phase Name (Русский)" },
            { name: "duration", type: "string", title: "Duration (English)" },
            { name: "durationRu", type: "string", title: "Duration (Русский)" },
            { name: "description", type: "text", rows: 3, title: "Description (English)" },
            { name: "descriptionRu", type: "text", rows: 3, title: "Description (Русский)" },
          ],
          preview: { select: { title: "phase", subtitle: "duration" } },
        },
      ],
    }),
    defineField({
      name: "challenge",
      title: "Challenge (English)",
      type: "text",
      group: "english",
      rows: 6,
      description: "Plain-text section — what was hard before the program.",
    }),
    defineField({
      name: "challengeRu",
      title: "Challenge (Русский)",
      type: "text",
      group: "russian",
      rows: 6,
    }),
    defineField({
      name: "solution",
      title: "Solution (English)",
      type: "text",
      group: "english",
      rows: 6,
    }),
    defineField({
      name: "solutionRu",
      title: "Solution (Русский)",
      type: "text",
      group: "russian",
      rows: 6,
    }),
    defineField({
      name: "results",
      title: "Results (English)",
      type: "text",
      group: "english",
      rows: 6,
    }),
    defineField({
      name: "resultsRu",
      title: "Results (Русский)",
      type: "text",
      group: "russian",
      rows: 6,
    }),
    defineField({
      name: "pullQuote",
      title: "Pull Quote (English)",
      type: "text",
      group: "english",
      rows: 3,
      description:
        "A single powerful line from their story — displayed large on the site.",
    }),
    defineField({
      name: "pullQuoteRu",
      title: "Pull Quote (Русский)",
      type: "text",
      group: "russian",
      rows: 3,
    }),
    defineField({
      name: "year",
      title: "Year",
      type: "number",
      group: "details",
      validation: (R) => R.min(2020).max(2030),
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "featured",
      title: "Feature on homepage?",
      type: "boolean",
      group: "details",
      initialValue: false,
    }),
    defineField({
      name: "active",
      title: "Active?",
      type: "boolean",
      group: "details",
      initialValue: true,
      description: "Untick to hide without deleting.",
    }),
    defineField({
      name: "order",
      title: "Display Order",
      type: "number",
      group: "details",
      initialValue: 10,
    }),
  ],
  orderings: [
    {
      title: "Display Order",
      name: "orderAsc",
      by: [{ field: "order", direction: "asc" }],
    },
  ],
  preview: {
    select: { title: "title", subtitle: "name", media: "photo", active: "active" },
    prepare({ title, subtitle, media, active }) {
      return {
        title: active === false ? `[HIDDEN] ${title ?? "Untitled"}` : title,
        subtitle,
        media,
      };
    },
  },
});
